services:
  go_app:
    build: .
    container_name: go_app_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      DB_HOST: ${DB_HOST:-postgres_db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-yakkaw}
      DB_PASSWORD: ${DB_PASSWORD:-1234}
      DB_NAME: ${DB_NAME:-yakkaw_db}
      SERVER_PORT: ${SERVER_PORT:-8080}

  postgres_db:
    image: postgres:latest
    container_name: postgres_db_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-${DB_USER:-yakkaw}}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-${DB_PASSWORD:-1234}}
      POSTGRES_DB: ${POSTGRES_DB:-${DB_NAME:-yakkaw_db}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
